version: '3'

services:

  imagery-service:
    privileged: true
    image: us.gcr.io/echoparklabs/gcp-imagery-service:latest
    ports:
      - "50051"

  imagery-client:
    image: us.gcr.io/echoparklabs/gcp-grpc-imagery-python:latest
    environment:
      IMAGERY_SERVICE: imagery-service:50051

    command: ["/bin/bash", "-c", "pip3 install pytest; pip3 install requests; pip3 install shapely; cd test; pytest --verbose --junitxml=./testresults.xml reader.py; ls; cd ../"]
